mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant_menu.urls'))
]

restaurant_menu/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.MenuList.as_view(), name='home'),
    path("item/<int:pk>/", views.MenuItemDetails.as_view(), name="menu_item")
]

restaurant_menu/models.py
from django.db import models
from django.contrib.auth.models import User

MEAL_TYPE = (
    ("starters", "Starters"),
    ("salads", "Salads"),
    ("main_dishes", "Main Dishes"),
    ("desserts", "Desserts")
)

STATUS = (
    (0, "Unavailable"),
    (1, "Available")
)


class Item(models.Model):
    meal = models.CharField(max_length=1000, unique=True)
    description = models.CharField(max_length=2000)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    meal_type = models.CharField(max_length=200,choices=MEAL_TYPE)
    author = models.ForeignKey(User, on_delete=models.PROTECT)   # CASCADE, SET_NULL
    status = models.IntegerField(choices=STATUS, default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.meal

restaurant_menu/views.py
from django.shortcuts import render
from django.views import generic
from .models import Item, MEAL_TYPE


class MenuList(generic.ListView):
    queryset = Item.objects.order_by("-date_created")
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["meals"] = MEAL_TYPE
        return context


class MenuItemDetails(generic.DetailView):
    model = Item
    template_name = "menu_item_detail.html"

restaurant_menu/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Job Application Form</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container ">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

restaurant_menu/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>Restaurant Menu</h1>
    <ul class="list-group list-group-flush">
    {% for meal in meals %}
        <h2 class="pt-3">{{ meal.1 }}</h2>
            {% for row in item_list %}
                {% if row.meal_type == meal.0 %}
                    {% if row.status == 0 %}
                    <li class="list-group-item d-flex justify-content-between align-items-center border-0 pb-0">
                        <a href="{% url 'menu_item' row.pk %}"><h3><del>{{ row.meal }}</del></h3></a>
                        <span class="badge bg-primary rounded-pill">{{ row.price }}</span>
                    </li>
                    <li class="list-group-item pt-0">
                        <p><del>{{ row.description }}</del></p>
                    </li>
                    {% else %}
                    <li class="list-group-item d-flex justify-content-between align-items-center border-0 pb-0">
                        <a href="{% url 'menu_item' row.pk %}"><h3>{{ row.meal }}</h3></a>
                        <span class="badge bg-primary rounded-pill">{{ row.price }}</span>
                    </li>
                    <li class="list-group-item pt-0">
                        <p>{{ row.description }}</p>
                    </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
    {% endfor %}
    </ul>
</div>
{% endblock content %}

restaurant_menu/templates/menu_item_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>{{ item.meal }}</h1>
        <p>{{ item.description }}</p>
        <p>{{ item.price }}</p>
    </div>
{% endblock content %}